<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PortfolioApp.Application\PortfolioApp.Application.csproj" />
    <ProjectReference Include="..\PortfolioApp.Domain\PortfolioApp.Domain.csproj" />
    <ProjectReference Include="..\PortfolioApp.Infrastructure.EfCore\PortfolioApp.Infrastructure.EfCore.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />

  <ItemGroup>
    <ProjectReference Include="..\portfolio-ui\portfolio-ui.csproj" />
  </ItemGroup>

  <Target Name="CopyFrontendToWwwroot" AfterTargets="Build">
    <ItemGroup>
      <FrontendDist Include="..\portfolio-ui\dist\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(FrontendDist)"
          DestinationFolder="wwwroot\%(RecursiveDir)"
          SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyFrontendOnPublish" AfterTargets="Publish">
    <ItemGroup>
      <FrontendDist Include="..\portfolio-ui\dist\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(FrontendDist)"
          DestinationFolder="$(PublishDir)wwwroot\%(RecursiveDir)"
          SkipUnchangedFiles="true" />
  </Target>
  
  <ItemGroup>
    <Content Include="..\..\Database\**\*">
      <Link>Database\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
